### PR TITLE
[Draft] Release 2.5.0 Docs

### PR DESCRIPTION
**Pull request by nathandyer**
## Status

Work in progress

## Description of Changes

Preparing for the 2.5.0 release.

Docs checklist:

- [x] Create a new upgrade guide copied from the most recent one and add it to the index.
- [x] Ensure that the latest_upgrade_guide reference at the top of the document is only present in the latest upgrade guide.
- [x] Remove the oldest upgrade guide and associated patch-level guides from the documentation.
- [x] Include the reminders in docs/includes/backup-and-update-reminders.txt towards the end of the document.
- [ ] Check with release manager about any other pertinent release-specific instructions that should be included.
- [x] Ensure that mentions of the current version are up to date.
- [x] Generate updated screenshots

## Release 

* This should not be merged until the 2.5.0 release is stable and available.

## Checklist (Optional)

- [x] Doc linting (`make docs-lint`) passed locally
- [x] Doc link linting (`make docs-linkcheck`) passed
- [x] You have previewed (`make docs`) docs at http://localhost:8000

### CODE REVIEW

**Comment by eloquence** [comment]
Hi @nathandyer! The boilerplate and version updates look good. Regarding the screenshot updates, there's one suggested change noted in our [docs](https://developers.securedrop.org/en/latest/documentation_guidelines.html):

> Configure the [New York World sample instance](https://github.com/freedomofpress/securedrop-ux/blob/main/User%20Testing/NYWorld%20Demo%20Site/logo.png) logo. Because the functional tests used to generate the logo may themselves update the logo, it is safest to temporarily overwrite the stock logo in securedrop/static/i/logo.png in your SecureDrop repository checkout.

The idea is to showcase SecureDrop with a logo other than the stock logo. I note that the logo image is actually broken in the screenshots you're replacing, so it's clearly an improvement! :) But if you do have time, that would be nice to update.

**Comment by nathandyer** [comment]
Thanks @eloquence! I'll take a look and get that updated this afternoon.

**Comment by eloquence** [comment]
Thanks, Nathan! Sorry for the hassle with the logo - it does look like we have the custom logo in some screenshots now but not others. One hypothesis why this might have happened is that the functional tests themselves update the logo and may have reinstated the stock logo. In the developer docs it says:

>  Because the functional tests used to generate the logo may themselves update the logo, it is safest to temporarily overwrite the stock logo in securedrop/static/i/logo.png in your SecureDrop repository checkout.

Is that the process you followed, and it still resulted in inconsistent screenshots? If so, we may want to poke a bit more at why that happened and update our docs.

**Comment by nathandyer** [comment]
@eloquence Yes, that's the process I followed (replacing the generic `securedrop/static/i/logo.png` file in my repository checkout with the NY World example logo). I'll take a look to see if I can figure out why it's inconsistently applying the logo.

**Review by eloquence — APPROVED** [review]
Approving as-is (we can follow up on SecureDrop/NY World logo inconsistencies in screenshots at a later time).

**Pull request merged**
