### PR TITLE
Update screenshots for SecureDrop 1.7.0

### LINKED ISSUE #121: Update screenshots for 1.7.0
The screenshots in the docs haven't been updated since 1.5.0. A few changes with UI implications have landed since then, e.g., https://github.com/freedomofpress/securedrop/pull/5593, https://github.com/freedomofpress/securedrop/pull/5593 and https://github.com/freedomofpress/securedrop/pull/5641.  We should update them for 1.7.0, including in Weblate.

### PR DESCRIPTION
**Pull request by eloquence**
## Status
Ready for review

## Description of Changes

- Also fixes wording for "New Identity" instructions
- Standardizes logo to NYWorld logo (except for the "Change logo"
  page) to reinforce that logo is typically customized

Resolves #121
## Note to reviewer

GitHub's "rich diff" on the Files Tab (the button next to `<>` for each file) is useful for screenshot comparisons.

## Checklist (Optional)

- [x] Doc linting (`make docs-lint`) passed locally
- [x] You have previewed (`make docs`) docs at http://localhost:8000

### CODE REVIEW

**Review by gonzalo-bulnes — COMMENTED** [review]
The new version of the file `docs/images/manual/screenshots/journalist-admin_system_config_page.png` displays a SecureDrop logo. (And it is wider than the other images: 1061px instead of 1024px?)

**Comment by eloquence** [comment]
Thanks @gonzalo-bulnes, good catch but intentional in this case: this section of the documentation shows how to change the stock logo to a custom one. (The width inconsistency is the result of these screenshots being taken manually rather than being generated via the functional tests; RTD will auto-scale them so it shouldn't be noticeably different in practice.)

**Comment by eloquence** [comment]
(Rebased.)

**Review by zenmonkeykstop — APPROVED** [review]
LGTM based on visual review.

**Pull request merged**
