### PR TITLE
Offer workaround for "Too any authentication failures" issue

### PR DESCRIPTION
**Pull request by eloquence**
## Status

Ready for review

## Description of Changes

Describes how to work around "Too many authentication failures" issue with SSH in the Molecule upgrade scenario.

## Checklist (Optional)

- [x] Doc linting (`make docs-lint`) passed locally
- [ ] Doc link linting (`make docs-linkcheck`) passed
- [x] You have previewed (`make docs`) docs at http://localhost:8000

### CODE REVIEW

**Comment by zenmonkeykstop** [comment]
Could this be solved by specifying "-o IdentitiesOnly=yes" as an argument to SSH in this scenario's `molecule.yml`?

**Comment by conorsch** [comment]
Almost certainly. Although, do we understand why it occurred in the upgrade scenario, but not in other scenarios?

**Comment by eloquence** [comment]
I've tested a patch by @zenmonkeykstop that resolves the issue for me and should make it unnecessary to further clutter our documentation, so I'm closing this PR.

**Comment by zenmonkeykstop** [comment]
@conorsch I would imagine it would be triggered in others depending on the SSH keys present.

**Pull request closed without merging**
